### ISSUE TITLE
Make erroring out without stack trace

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#252]
For example, that kind of stack trace erroring:
```
[lbsVTDataReader] Reading ~/LB-analysis-framework/data/nolb-8color-16nodes-data/data.0.json VT object map
Traceback (most recent call last):
  File "LBAF_app.py", line 327, in <module>
    LBAFApp().main()
  File "LBAF_app.py", line 185, in main
    phase.populate_from_log(
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/Model/lbsPhase.py", line 238, in populate_from_log
    self.__ranks = reader.read_iteration(n_ranks, t_s)
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/IO/lbsVTDataReader.py", line 82, in read_iteration
    rank_iter_map, rank_comm = self.read(p, phase_id)
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/IO/lbsVTDataReader.py", line 58, in read
    iter_map, comm = self.json_reader(
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/IO/lbsVTDataReader.py", line 139, in json_reader
    raise TypeError("JSON data is missing 'type' key")
TypeError: JSON data is missing 'type' key
```
is not the desired behavior. We should have a clean error message, and not a stack trace, consistent with how it used to be done throughout LBAF:
1. Invocation of the logger in error mode
2. Termination without a stack trace.

Also please remove all occurrences of `!` exclamation marks in messages.

**Comment by ppebay** [comment]
@marcinwrobel1986 wasn't this one also resolved by PR #250 ?
