### ISSUE TITLE
nolb example no longer working

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#253]
Not sure what happened after the last merge, but this configuration is no longer working (it's working pre-merge):

```
[lbsVTDataReader] Reading ~/Documents/Git/LB-analysis-framework/data/nolb-8color-16nodes-data/data.0.json VT object map
Traceback (most recent call last):
  File "LBAF_app.py", line 327, in <module>
    LBAFApp().main()
  File "LBAF_app.py", line 185, in main
    phase.populate_from_log(
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/Model/lbsPhase.py", line 238, in populate_from_log
    self.__ranks = reader.read_iteration(n_ranks, t_s)
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/IO/lbsVTDataReader.py", line 82, in read_iteration
    rank_iter_map, rank_comm = self.read(p, phase_id)
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/IO/lbsVTDataReader.py", line 58, in read
    iter_map, comm = self.json_reader(
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/IO/lbsVTDataReader.py", line 139, in json_reader
    raise TypeError("JSON data is missing 'type' key")
TypeError: JSON data is missing 'type' key
```

**Comment by marcinwrobel1986** [comment]
Hi, yes.
now, or better say since we merged the changes, type of the data must be given and it must be "LBDatafile" or "LBStatsfile"
Any old data files needs to be modified in order to work.
