### ISSUE TITLE
KeyError when writing vtp mesh with dynamic collections

### ISSUE THREAD

**Issue by nmm0** [DARMA-tasking/LB-analysis-framework#283]
I'm trying to write out the visualization of a series of timesteps but am getting the following error after analysis is complete and when LBAF is trying to write the output mesh:

```
Traceback (most recent call last):
  File "LB-analysis-framework/src/lbaf/Applications/LBAF_app.py", line 330, in <module>
    LBAFApp().main()
  File "LB-analysis-framework/src/lbaf/Applications/LBAF_app.py", line 297, in main
    ex_writer.generate(gen_meshes, gen_mulmed)
  File "LB-analysis-framework/src/lbaf/IO/lbsMeshBasedVisualizer.py", line 587, in generate
    object_mesh = self.create_object_mesh(phase, object_mapping)
  File "LB-analysis-framework/src/lbaf/IO/lbsMeshBasedVisualizer.py", line 271, in create_object_mesh
    points.SetPoint(point_index, [
  File "LB-analysis-framework/src/lbaf/IO/lbsMeshBasedVisualizer.py", line 273, in <listcomp>
    self.__jitter_dims[o.get_id()][d] + c) * o_resolution
KeyError: 11796483
```

I think it's related to objects being inserted into some collections.

**Comment by nlslatt** [comment]
@ppebay We need to add previously unseen object IDs to the jitter data structure as they are encountered.

**Comment by marcinwrobel1986** [comment]
yup, definitely Philippe's stuff

**Comment by ppebay** [comment]
@nmm0 ate you still seeing this issue, or is fixed with the recent changes to LBAF-Viz? Thanks

**Comment by nmm0** [comment]
We fixed the crash in https://github.com/DARMA-tasking/LB-analysis-framework/pull/288 but we still might want to generate a random jitter so we don't have all the inserted objects overlapping

**Comment by cwschilly** [comment]
This issue has been relocated to [vt-tv #76](https://github.com/DARMA-tasking/vt-tv/issues/76), since LBAF Viz has been deprecated.
