### ISSUE TITLE
Changes to validator causing LBAF branch 279 to crash

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#295]
```
[LBAF_app] Saved SchemaValidator to: /Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/imported/JSON_data_files_validator.py
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/IO/lbsVTDataWriter.py", line 83, in json_writer
    "load": task["obj_time"],
KeyError: 'obj_time'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "LBAF_app.py", line 385, in <module>
    LBAFApp().main()
  File "LBAF_app.py", line 336, in main
    vt_writer.write()
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/IO/lbsVTDataWriter.py", line 44, in write
    for file_name in results:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
KeyError: 'obj_time'
```

**Comment by ppebay** [comment]
There seems to be a conflict between old and new schemata, regarding `obj_time` (vs. `obj_load`?). @marcinwrobel1986

**Comment by marcinwrobel1986** [comment]
@ppebay Hello Philippe,
what I can do here is:
- merge latest develop to your branch
- resolve conflicts (if there would be any)
- make sure branch is working and push the merged changes

I am starting now. Please don't work on the branch till I will let you know that is safe to work.
Hear you in a bit.

**Comment by marcinwrobel1986** [comment]
Ok, from my side this error is fixed.
Please take a look at line 293 in `LBAF_app.py` when `brute_force_optimization` is on.
The below casusing and error. I assume this is due to renaming time and load.
```Python3
                        "time": o.get_time(),
```

**Comment by ppebay** [comment]
Thanks @marcinwrobel1986 this one seems solved now

**Comment by ppebay** [comment]
Marking as resolved, thanks
