### ISSUE TITLE
SchemaValidator execution error in develop branch

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#310]
In current `develop`, executing:
```
python LBAF_app.py --config=conf.yaml
``` 
getting the following error:
```
[LBAF_app] Saved SchemaValidator to: /Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/imported/JSON_data_files_validator.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/Applications/LBAF_app.py", line 80, in <module>
    from lbaf.Applications.rank_object_enumerator import compute_min_max_arrangements_work
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/Applications/rank_object_enumerator.py", line 16, in <module>
    from lbaf.IO.lbsVTDataReader import LoadReader
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/IO/lbsVTDataReader.py", line 9, in <module>
    from ..imported.JSON_data_files_validator import SchemaValidator
ImportError: cannot import name 'SchemaValidator' from 'lbaf.imported.JSON_data_files_validator' (/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/imported/JSON_data_files_validator.py)
```

**Comment by marcinwrobel1986** [comment]
Hello Philippe,
my terminal output:
```bash
(venv)  marcin@pop-os  ~/Dokumenty/NGA/projects/LB-analysis-framework   develop  git pull            
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Total 6 (delta 4), reused 6 (delta 4), pack-reused 0
Unpacking objects: 100% (6/6), 1.16 KiB | 394.00 KiB/s, done.
From github.com:DARMA-tasking/LB-analysis-framework
   a9caaf6..5945d93  305-fix-incorrect-rank-instantiation-in-JSON-VT-reader -> origin/305-fix-incorrect-rank-instantiation-in-JSON-VT-reader
Already up to date.
(venv)  marcin@pop-os  ~/Dokumenty/NGA/projects/LB-analysis-framework   develop  git status
On branch develop
Your branch is up to date with 'origin/develop'.
(venv)  marcin@pop-os  ~/Dokumenty/NGA/projects/LB-analysis-framework   develop  git pull  
Already up to date.
(venv)  marcin@pop-os  ~/Dokumenty/NGA/projects/LB-analysis-framework   develop  python src/lbaf/Applications/LBAF_app.py --config=src/lbaf/Applications/conf.yaml
[LBAF_app] Saved SchemaValidator to: /home/marcin/Dokumenty/NGA/projects/LB-analysis-framework/src/lbaf/imported/JSON_data_files_validator.py
[LBAF_app] Executing LBAF version 0.1.0rc1
[LBAF_app] Executing with Python 3.8.13
[LBAF_app] Found configuration file /home/marcin/Dokumenty/NGA/projects/LB-analysis-framework/src/lbaf/Applications/conf.yaml
[configurationValidator] Skeleton schema is valid
[configurationValidator] Reading from data was chosen
[configurationValidator] from_data schema is valid
[configurationValidator] Checking algorithm schema of: InformAndTransfer
[configurationValidator] Algorithm: InformAndTransfer schema is valid
[LBAF_app] Logging level: info
[LBAF_app] Output directory: /home/marcin/Dokumenty/output
[lbsVTDataReader] Reading /home/marcin/Dokumenty/NGA/projects/LB-analysis-framework/data/synthetic_lb_data/data.0.json VT object map
[lbsVTDataReader] Reading /home/marcin/Dokumenty/NGA/projects/LB-analysis-framework/data/synthetic_lb_data/data.1.json VT object map
[lbsVTDataReader] Reading /home/marcin/Dokumenty/NGA/projects/LB-analysis-framework/data/synthetic_lb_data/data.2.json VT object map
[lbsVTDataReader] Reading /home/marcin/Dokumenty/NGA/projects/LB-analysis-framework/data/synthetic_lb_data/data.3.json VT object map
[lbsStatistics] Descriptive statistics of object times:
[lbsStatistics]         cardinality: 9  sum: 8  imbalance: 1.25
[lbsStatistics]         minimum: 0.5  mean: 0.888889  maximum: 2
[lbsStatistics]         standard deviation: 0.515201  variance: 0.265432
[lbsStatistics]         skewness: 1.06328  kurtosis excess: -0.195511
[lbsPhase] Read 9 objects from time-step 0 of data files with prefix /home/marcin/Dokumenty/NGA/projects/LB-analysis-framework/data/synthetic_lb_data/data
[lbsStatistics] Descriptive statistics of initial rank loads:
[lbsStatistics]         cardinality: 4  sum: 8  imbalance: 1
[lbsStatistics]         minimum: 0  mean: 2  maximum: 4
[lbsStatistics]         standard deviation: 1.45774  variance: 2.125
[lbsStatistics]         skewness: 4.48004e-17  kurtosis excess: -1.22145
[lbsStatistics] Inter-rank communication edges: 3 amongst possible ones: 6 (50%)
[lbsStatistics] Rank-local communication volume: 2 amongst total volume: 11 (18.2%)
[lbsStatistics] Descriptive statistics of initial sent volumes:
[lbsStatistics]         cardinality: 3  sum: 5.5  imbalance: 0.636364
[lbsStatistics]         minimum: 0.5  mean: 1.83333  maximum: 3
[lbsStatistics]         standard deviation: 1.0274  variance: 1.05556
[lbsStatistics]         skewness: -0.239063  kurtosis excess: -1.5
[LBAF_app] No brute force optimization performed
[lbsAffineCombinationWorkModel] Instantiated work model with alpha=1.0, beta=0.0, gamma=0.0
[lbsInformAndTransferAlgorithm] Instantiated with 8 iterations, 4 rounds, fanout 4
[lbsInformAndTransferAlgorithm] Selected arbitrary object ordering strategy
[lbsTemperedCriterion] Instantiated TemperedCriterion concrete criterion
[lbsRuntime] Instantiated with 0 optimal arrangements for Hamming distance comparison
[lbsStatistics] Descriptive statistics of initial rank works:
[lbsStatistics]         cardinality: 4  sum: 8  imbalance: 1
[lbsStatistics]         minimum: 0  mean: 2  maximum: 4
[lbsStatistics]         standard deviation: 1.45774  variance: 2.125
[lbsStatistics]         skewness: 4.48004e-17  kurtosis excess: -1.22145
[lbsRuntime] Executing InformAndTransferAlgorithm
[lbsInformAndTransferAlgorithm] Starting iteration 1
[lbsInformAndTransferAlgorithm] Initializing information messages with fanout=4
[lbsInformAndTransferAlgorithm] Completed 4 information rounds
[lbsInformAndTransferAlgorithm] Reporting viewers counts (min:3, mean: 3 max: 3) to 3 loaded ranks
[lbsInformAndTransferAlgorithm] Executing transfer phase
[lbsInformAndTransferAlgorithm] Maximum number of objects transferred at once: 1
[lbsInformAndTransferAlgorithm] 13 proposed transfers, 6 occurred, 7 rejected (53.85%)
[lbsInformAndTransferAlgorithm] Iteration complete (0 skipped ranks)
[lbsStatistics] Descriptive statistics of iteration 1 rank works:
[lbsStatistics]         cardinality: 4  sum: 8  imbalance: 0.5
[lbsStatistics]         minimum: 1.5  mean: 2  maximum: 3
[lbsStatistics]         standard deviation: 0.612372  variance: 0.375
[lbsStatistics]         skewness: 0.816497  kurtosis excess: -1
[lbsStatistics] Inter-rank communication edges: 4 amongst possible ones: 6 (66.7%)
[lbsStatistics] Rank-local communication volume: 4 amongst total volume: 11 (36.4%)
[lbsInformAndTransferAlgorithm] Starting iteration 2
[lbsInformAndTransferAlgorithm] Initializing information messages with fanout=4
[lbsInformAndTransferAlgorithm] Completed 4 information rounds
[lbsInformAndTransferAlgorithm] Reporting viewers counts (min:4, mean: 4 max: 4) to 4 loaded ranks
[lbsInformAndTransferAlgorithm] Executing transfer phase
[lbsInformAndTransferAlgorithm] Maximum number of objects transferred at once: 1
[lbsInformAndTransferAlgorithm] 11 proposed transfers, 4 occurred, 7 rejected (63.64%)
[lbsInformAndTransferAlgorithm] Iteration complete (0 skipped ranks)
[lbsStatistics] Descriptive statistics of iteration 2 rank works:
[lbsStatistics]         cardinality: 4  sum: 8  imbalance: 0
[lbsStatistics]         minimum: 2  mean: 2  maximum: 2
[lbsStatistics]         standard deviation: 0  variance: 0
[lbsStatistics]         skewness: nan  kurtosis excess: nan
[lbsStatistics] Inter-rank communication edges: 5 amongst possible ones: 6 (83.3%)
[lbsStatistics] Rank-local communication volume: 1.5 amongst total volume: 11 (13.6%)
[lbsInformAndTransferAlgorithm] Starting iteration 3
[lbsInformAndTransferAlgorithm] Initializing information messages with fanout=4
[lbsInformAndTransferAlgorithm] Completed 4 information rounds
[lbsInformAndTransferAlgorithm] Reporting viewers counts (min:4, mean: 4 max: 4) to 4 loaded ranks
[lbsInformAndTransferAlgorithm] Executing transfer phase
[lbsInformAndTransferAlgorithm] Maximum number of objects transferred at once: 0
[lbsInformAndTransferAlgorithm] 9 proposed transfers, 0 occurred, 9 rejected (100.0%)
[lbsInformAndTransferAlgorithm] Iteration complete (0 skipped ranks)
[lbsStatistics] Descriptive statistics of iteration 3 rank works:
[lbsStatistics]         cardinality: 4  sum: 8  imbalance: 0
[lbsStatistics]         minimum: 2  mean: 2  maximum: 2
[lbsStatistics]         standard deviation: 0  variance: 0
[lbsStatistics]         skewness: nan  kurtosis excess: nan
[lbsStatistics] Inter-rank communication edges: 5 amongst possible ones: 6 (83.3%)
[lbsStatistics] Rank-local communication volume: 1.5 amongst total volume: 11 (13.6%)
[lbsInformAndTransferAlgorithm] Starting iteration 4
[lbsInformAndTransferAlgorithm] Initializing information messages with fanout=4
[lbsInformAndTransferAlgorithm] Completed 4 information rounds
[lbsInformAndTransferAlgorithm] Reporting viewers counts (min:4, mean: 4 max: 4) to 4 loaded ranks
[lbsInformAndTransferAlgorithm] Executing transfer phase
[lbsInformAndTransferAlgorithm] Maximum number of objects transferred at once: 0
[lbsInformAndTransferAlgorithm] 9 proposed transfers, 0 occurred, 9 rejected (100.0%)
[lbsInformAndTransferAlgorithm] Iteration complete (0 skipped ranks)
[lbsStatistics] Descriptive statistics of iteration 4 rank works:
[lbsStatistics]         cardinality: 4  sum: 8  imbalance: 0
[lbsStatistics]         minimum: 2  mean: 2  maximum: 2
[lbsStatistics]         standard deviation: 0  variance: 0
[lbsStatistics]         skewness: nan  kurtosis excess: nan
[lbsStatistics] Inter-rank communication edges: 5 amongst possible ones: 6 (83.3%)
[lbsStatistics] Rank-local communication volume: 1.5 amongst total volume: 11 (13.6%)
[lbsInformAndTransferAlgorithm] Starting iteration 5
[lbsInformAndTransferAlgorithm] Initializing information messages with fanout=4
[lbsInformAndTransferAlgorithm] Completed 4 information rounds
[lbsInformAndTransferAlgorithm] Reporting viewers counts (min:4, mean: 4 max: 4) to 4 loaded ranks
[lbsInformAndTransferAlgorithm] Executing transfer phase
[lbsInformAndTransferAlgorithm] Maximum number of objects transferred at once: 0
[lbsInformAndTransferAlgorithm] 9 proposed transfers, 0 occurred, 9 rejected (100.0%)
[lbsInformAndTransferAlgorithm] Iteration complete (0 skipped ranks)
[lbsStatistics] Descriptive statistics of iteration 5 rank works:
[lbsStatistics]         cardinality: 4  sum: 8  imbalance: 0
[lbsStatistics]         minimum: 2  mean: 2  maximum: 2
[lbsStatistics]         standard deviation: 0  variance: 0
[lbsStatistics]         skewness: nan  kurtosis excess: nan
[lbsStatistics] Inter-rank communication edges: 5 amongst possible ones: 6 (83.3%)
[lbsStatistics] Rank-local communication volume: 1.5 amongst total volume: 11 (13.6%)
[lbsInformAndTransferAlgorithm] Starting iteration 6
[lbsInformAndTransferAlgorithm] Initializing information messages with fanout=4
[lbsInformAndTransferAlgorithm] Completed 4 information rounds
[lbsInformAndTransferAlgorithm] Reporting viewers counts (min:4, mean: 4 max: 4) to 4 loaded ranks
[lbsInformAndTransferAlgorithm] Executing transfer phase
[lbsInformAndTransferAlgorithm] Maximum number of objects transferred at once: 0
[lbsInformAndTransferAlgorithm] 9 proposed transfers, 0 occurred, 9 rejected (100.0%)
[lbsInformAndTransferAlgorithm] Iteration complete (0 skipped ranks)
[lbsStatistics] Descriptive statistics of iteration 6 rank works:
[lbsStatistics]         cardinality: 4  sum: 8  imbalance: 0
[lbsStatistics]         minimum: 2  mean: 2  maximum: 2
[lbsStatistics]         standard deviation: 0  variance: 0
[lbsStatistics]         skewness: nan  kurtosis excess: nan
[lbsStatistics] Inter-rank communication edges: 5 amongst possible ones: 6 (83.3%)
[lbsStatistics] Rank-local communication volume: 1.5 amongst total volume: 11 (13.6%)
[lbsInformAndTransferAlgorithm] Starting iteration 7
[lbsInformAndTransferAlgorithm] Initializing information messages with fanout=4
[lbsInformAndTransferAlgorithm] Completed 4 information rounds
[lbsInformAndTransferAlgorithm] Reporting viewers counts (min:4, mean: 4 max: 4) to 4 loaded ranks
[lbsInformAndTransferAlgorithm] Executing transfer phase
[lbsInformAndTransferAlgorithm] Maximum number of objects transferred at once: 0
[lbsInformAndTransferAlgorithm] 9 proposed transfers, 0 occurred, 9 rejected (100.0%)
[lbsInformAndTransferAlgorithm] Iteration complete (0 skipped ranks)
[lbsStatistics] Descriptive statistics of iteration 7 rank works:
[lbsStatistics]         cardinality: 4  sum: 8  imbalance: 0
[lbsStatistics]         minimum: 2  mean: 2  maximum: 2
[lbsStatistics]         standard deviation: 0  variance: 0
[lbsStatistics]         skewness: nan  kurtosis excess: nan
[lbsStatistics] Inter-rank communication edges: 5 amongst possible ones: 6 (83.3%)
[lbsStatistics] Rank-local communication volume: 1.5 amongst total volume: 11 (13.6%)
[lbsInformAndTransferAlgorithm] Starting iteration 8
[lbsInformAndTransferAlgorithm] Initializing information messages with fanout=4
[lbsInformAndTransferAlgorithm] Completed 4 information rounds
[lbsInformAndTransferAlgorithm] Reporting viewers counts (min:4, mean: 4 max: 4) to 4 loaded ranks
[lbsInformAndTransferAlgorithm] Executing transfer phase
[lbsInformAndTransferAlgorithm] Maximum number of objects transferred at once: 0
[lbsInformAndTransferAlgorithm] 9 proposed transfers, 0 occurred, 9 rejected (100.0%)
[lbsInformAndTransferAlgorithm] Iteration complete (0 skipped ranks)
[lbsStatistics] Descriptive statistics of iteration 8 rank works:
[lbsStatistics]         cardinality: 4  sum: 8  imbalance: 0
[lbsStatistics]         minimum: 2  mean: 2  maximum: 2
[lbsStatistics]         standard deviation: 0  variance: 0
[lbsStatistics]         skewness: nan  kurtosis excess: nan
[lbsStatistics] Inter-rank communication edges: 5 amongst possible ones: 6 (83.3%)
[lbsStatistics] Rank-local communication volume: 1.5 amongst total volume: 11 (13.6%)
[lbsVTDataWriter] Wrote 1 objects to /home/marcin/Dokumenty/output/output_file.0.vom
[lbsVTDataWriter] Wrote 3 objects to /home/marcin/Dokumenty/output/output_file.1.vom
[lbsVTDataWriter] Saved /home/marcin/Dokumenty/output/output_file.0.vom
[lbsVTDataWriter] Saved /home/marcin/Dokumenty/output/output_file.1.vom
[lbsVTDataWriter] Wrote 2 objects to /home/marcin/Dokumenty/output/output_file.2.vom
[lbsVTDataWriter] Wrote 3 objects to /home/marcin/Dokumenty/output/output_file.3.vom
[lbsVTDataWriter] Saved /home/marcin/Dokumenty/output/output_file.2.vom
[lbsVTDataWriter] Saved /home/marcin/Dokumenty/output/output_file.3.vom
[lbsMeshBasedVisualizer] Creating rank mesh with 4 points and 6 edges
[lbsGridStreamer] Streaming 9 load-balancing steps
[lbsMeshBasedVisualizer] Writing ExodusII file: /home/marcin/Dokumenty/output/output_file_rank_view.e
[lbsMeshBasedVisualizer] Creating object mesh with 9 points and 36 edges
[lbsMeshBasedVisualizer] Writing VTP file: /home/marcin/Dokumenty/output/output_file_object_view_00.vtp
[lbsMeshBasedVisualizer] Creating object mesh with 9 points and 36 edges
[lbsMeshBasedVisualizer] Writing VTP file: /home/marcin/Dokumenty/output/output_file_object_view_01.vtp
[lbsMeshBasedVisualizer] Creating object mesh with 9 points and 36 edges
[lbsMeshBasedVisualizer] Writing VTP file: /home/marcin/Dokumenty/output/output_file_object_view_02.vtp
[lbsMeshBasedVisualizer] Creating object mesh with 9 points and 36 edges
[lbsMeshBasedVisualizer] Writing VTP file: /home/marcin/Dokumenty/output/output_file_object_view_03.vtp
[lbsMeshBasedVisualizer] Creating object mesh with 9 points and 36 edges
[lbsMeshBasedVisualizer] Writing VTP file: /home/marcin/Dokumenty/output/output_file_object_view_04.vtp
[lbsMeshBasedVisualizer] Creating object mesh with 9 points and 36 edges
[lbsMeshBasedVisualizer] Writing VTP file: /home/marcin/Dokumenty/output/output_file_object_view_05.vtp
[lbsMeshBasedVisualizer] Creating object mesh with 9 points and 36 edges
[lbsMeshBasedVisualizer] Writing VTP file: /home/marcin/Dokumenty/output/output_file_object_view_06.vtp
[lbsMeshBasedVisualizer] Creating object mesh with 9 points and 36 edges
[lbsMeshBasedVisualizer] Writing VTP file: /home/marcin/Dokumenty/output/output_file_object_view_07.vtp
[lbsMeshBasedVisualizer] Creating object mesh with 9 points and 36 edges
[lbsMeshBasedVisualizer] Writing VTP file: /home/marcin/Dokumenty/output/output_file_object_view_08.vtp
[lbsStatistics] Descriptive statistics of final rank loads:
[lbsStatistics] Final imbalance: 0.0 logged to /home/marcin/Dokumenty/output/imbalance.txt
[lbsStatistics]         cardinality: 4  sum: 8  imbalance: 0
[lbsStatistics]         minimum: 2  mean: 2  maximum: 2
[lbsStatistics]         standard deviation: 0  variance: 0
[lbsStatistics]         skewness: nan  kurtosis excess: nan
[lbsStatistics] Descriptive statistics of final sent volumes:
[lbsStatistics]         cardinality: 5  sum: 8.5  imbalance: 0.176471
[lbsStatistics]         minimum: 1  mean: 1.7  maximum: 2
[lbsStatistics]         standard deviation: 0.4  variance: 0.16
[lbsStatistics]         skewness: -0.84375  kurtosis excess: -0.921875
[LBAF_app] Optimal load statistics for 9 objects with iso-time: 0.888889
[LBAF_app]      minimum: 1.77778  maximum: 2.66667
[LBAF_app]      standard deviation: 0.3849 imbalance: 0.333333
[LBAF_app] Process completed without errors
```

**Comment by ppebay** [comment]
@marcinwrobel1986 while it's great that it is working in your system, it's not working on mine and it's also failing in CI

**Comment by marcinwrobel1986** [comment]
@ppebay yup, checking further. Just want to make a point I haven't noticed anything on my machine

**Comment by marcinwrobel1986** [comment]
@ppebay seems like it is working well on CI as well.
It failed only because of the 0.25 imbalance, but have no problems regarding importing modules [LINK](https://github.com/DARMA-tasking/LB-analysis-framework/actions/runs/3438400741/jobs/5815087516)

**Comment by marcinwrobel1986** [comment]
@ppebay In #307 unit tests are failing, because you renamed variables. Please make sure you rename them in Unit tests as well

**Comment by marcinwrobel1986** [comment]
@ppebay I have re-ran acceptance tests [LINK](https://github.com/DARMA-tasking/LB-analysis-framework/actions/runs/3477975463) in #307 and they are passing.

**Comment by ppebay** [comment]
Which variables specifically?

**Comment by ppebay** [comment]
@marcinwrobel1986 the `SchemaValidator` error I described was happening on my local MacOS system *before I changed anything* when I pulled the latest `develop`. It has nothing to do with me changing variables.

**Comment by marcinwrobel1986** [comment]
> @ppebay I have re-ran acceptance tests [LINK](https://github.com/DARMA-tasking/LB-analysis-framework/actions/runs/3477975463) in #307 and they are passing.

[LINK](https://github.com/DARMA-tasking/LB-analysis-framework/actions/runs/3477975464/jobs/5814779824) to unit tests

![Zrzut ekranu z 2022-11-16 11-00-32](https://user-images.githubusercontent.com/47597569/202150004-370d3b15-6377-43c9-9948-ecd978f38aa7.png)

**Comment by marcinwrobel1986** [comment]
> @marcinwrobel1986 the `SchemaValidator` error I described was happening on my local MacOS system **before I changed anything** when I pulled the latest `develop`. It has nothing to do with me changing variables.
> 
> I just tried again to pull from `develop` and am getting the **same** error as described in this current issue.
> 
> Please note that this is an error we have seen before and you mentioned it had to do with multiprocessing module IIRC.

@ppebay SchemaValidator failing on your machine has nothing to do with the Unit tests, but you mentioned, that it is failing on CI, so I checked that and it is not.

I am looking currently for the changes I made in order to fix the issue you had on MacOS. I can not see them in develop.

Please give me a couple of minutes to track them...

**Comment by marcinwrobel1986** [comment]
Ok, prepared a PR #311

**Comment by ppebay** [comment]
Thanks!
