### ISSUE TITLE
bug with remaining confusion between object id and index

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#564]
## Steps to reproduce:
In `develop branch`, from `src/lbaf/Applications`, execute:
```
python LBAF_app.py  -c conf.yaml
```

## Description of the issue:
The following runtime error:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/pppebay/miniconda3/envs/lbaf39/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/IO/lbsVTDataWriter.py", line 279, in _json_writer
    serial_json = self._json_serializer(rank_phases_double)
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/IO/lbsVTDataWriter.py", line 251, in _json_serializer
    self.__create_tasks(
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/IO/lbsVTDataWriter.py", line 126, in __create_tasks
    if o.get_index() is not None:
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/Model/lbsObject.py", line 184, in get_index
    return self.__index
AttributeError: 'Object' object has no attribute '_Object__index'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/Applications/LBAF_app.py", line 693, in <module>
    LBAFApplication().run()
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/Applications/LBAF_app.py", line 623, in run
    self.__json_writer.write(
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/IO/lbsVTDataWriter.py", line 316, in write
    for file_name in results:
  File "/Users/pppebay/miniconda3/envs/lbaf39/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
AttributeError: 'Object' object has no attribute '_Object__index'
```

**Comment by ppebay** [comment]
@lifflander this is related to what I was describing in a comment to PR #559
