### ISSUE TITLE
Post PR563 merge rendering error

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#575]
## Steps to reproduce:
* use branch 130 of vt-tv
* run `synthetic-blocks.yaml` test case of LBAF's `develop` branch (post merger of PR #563 )

## Description:
The following vt-tv runtime error occurs:
```
---- Normalizing Edges for phase 1 ----
Size of all objects: 9
Traceback (most recent call last):
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/Applications/LBAF_app.py", line 674, in <module>
    LBAFApplication().run()
  File "/Users/pppebay/Documents/Git/LB-analysis-framework/src/lbaf/Applications/LBAF_app.py", line 648, in run
    vttv.tvFromJson(ranks_json_str, str(vttv_params), num_ranks)
IndexError: unordered_map::at: key not found
```

**Comment by ppebay** [comment]
Investigating case as well, but also co-assigning @lifflander @pierrepebay in case you have an idea as to what is not correctly passed to vt-tv

**Comment by ppebay** [comment]
Here are the generated JSON files @pierrepebay 

[synthetic-dataset-blocks.0.json](https://github.com/user-attachments/files/18241345/synthetic-dataset-blocks.0.json)
[synthetic-dataset-blocks.1.json](https://github.com/user-attachments/files/18241346/synthetic-dataset-blocks.1.json)
[synthetic-dataset-blocks.2.json](https://github.com/user-attachments/files/18241347/synthetic-dataset-blocks.2.json)
[synthetic-dataset-blocks.3.json](https://github.com/user-attachments/files/18241348/synthetic-dataset-blocks.3.json)
